CLASS_NAME = "CLASS_NAME"
CLASS_SUPER = "CLASS_SUPER"
CLASS_IMPLEMENTS = "CLASS_IMPLEMENTS"
CLASS_METHODS = "CLASS_METHODS"
CLASS_FIELDS = "CLASS_FIELDS"

METHOD_PARAMS = "METHOD_PARAMS"
METHOD_RETURN = "METHOD_RETURN"

FIELD_NAME = "FIELD_NAME"
FIELD_TYPE = "FIELD_TYPE"
FIELD_INIT = "FIELD_INIT"

WITHLINES_SOURCECODE = "WITHLINES_SOURCECODE"
WITHLINES_NAME = "WITHLINES_NAME"

ANOT_MOD_MODIFIERS = "ANOT_MOD_MODIFIERS"
ANOT_MOD_ANNOTATIONS = "ANOT_MOD_ANNOTATIONS"

